- .travis.yml
- docs/v1/collection/sample.json
- docs/v1/collection/schema.json
- docs/v1/sponsor/sample.json
- docs/v1/sponsor/schema.json
- opac_schema/v1/models.py
- setup.py
- tests/__init__.py
- tests/test_article.py
- tests/test_collection.py
- tests/test_issue.py
- tests/test_sponsor.py
FIXES: #4 
Adiciona testes e documentação (arquivos sample.json e schema.json) de cada novo modelo.
> #4 - Novos modelos: Collection e Sponsor

- docs/v1/resource/sample.json
- docs/v1/resource/schema.json
- docs/v1/sponsor/sample.json
- opac_schema/v1/models.py
- tests/test_resource.py
- novo modelo Resoruce
- novos tests para o modelo Resouce
- ajustes nos sample e schema do sponsor e resource
- troca na importação para evitar ``import *`` (issue #1)
- FIX #11
- FIX #1
> Novo modelo resource + test + ajustes menores

- opac_schema/v1/models.py
- setup.py
> #27 - Remover licençias de Collection, Journal e Issue

- opac_schema/v1/models.py
- setup.py
Relacionado com o ticket: https://github.com/scieloorg/opac/issues/234
> Adicionando a lista de idiomas para o abstract

- opac_schema/v1/models.py
Adicionando o Press Release no Opac Schema.
> Adicionando o press release no opac_schema.

- opac_schema/v1/models.py
- setup.py
Adicionando o modelo de Press Release e ajustes nos __unicode__
> Adicionado o press release.

- opac_schema/v1/models.py
> Propriedade url no models do: Journal, Issue e Article

- opac_schema/v1/models.py
- setup.py
Relacionado à tarefa https://trello.com/c/V5ohoVDI/1-3-importar-e-exibir-press-releases-do-blog
issue https://github.com/scieloorg/opac/issues/321
> adiciona campo url no modelo press release

- opac_schema/v1/models.py
- setup.py
Fixes: https://github.com/scieloorg/opac/issues/583
> Regra para idioma da missão tk:583 (opac)

- .travis.yml
- opac_schema/v1/models.py
- setup.py
- tests/test_article.py
- tests/test_auditlog.py
- tests/test_collection.py
- tests/test_issue.py
- tests/test_journal.py
- tests/test_news.py
- tests/test_pages.py
- tests/test_press_releases.py
- tests/test_sponsor.py
and bump version number up to: v2.41
> add audit log entry model and some tests

- opac_schema/v1/models.py
- setup.py
Esse PR realiza as seguintes mudanças: 
- Adicionar o campo **aop_pid**
- Adicionar o **pid** e o **aop_pid** na lista de campos para indexação do Mongo.
> Adicionar novo campo para o ID do Ex-Ahead.

- opac_schema/v1/models.py
- setup.py
- tests/test_article.py
Além disso, ajustes na classe de testes: 
- Renomear TestIssueModel para TestArticleModel
- incluir Issue em model_class_to_delete
- Testes para Article.url com:
- elocation
- fpage e lpage
- fpage_seq
- doi
- order 
Fixes #69
> [tk69] Inclusão do campo fpage_sequence em Article

- opac_schema/v1/models.py
- setup.py
- tests/test_sponsor.py
Para determinar a ordem de prioridade para exibição no OPAC.
> Adiciona campo order no model Sponsor

- opac_schema/v1/models.py
- setup.py
- tests/test_journal.py
> [tk72] Incluir o atributo scimago_id em Journal

- opac_schema/v1/models.py
- setup.py
Inclusão de slug_name no modelo Pages
para atender https://github.com/scieloorg/opac/issues/1067
Fixes #74
> [Tk74] Inclusão de slug_name no modelo Pages

- opac_schema/v1/models.py
* Cria o metodos `url_new_journal` que através do campo `new_journal` ele ira buscar o novo periódico que esta substituindo esse periódico descontinuado 
* Cria o metodos `url_previous_journal` que através do campo `previous_journal` ele ira buscar periódico antigo que foi descontinuado 
pelo `models.py` na classe `Journal`
Esses metodos são utilizados para criar um referenciamento cruzado entre dois periódicos, sendo um descontinuado e o outro ativo e o ativo esta substituindo o descontinuado 
https://github.com/scieloorg/opac/issues/1117
> Add method 'url_new_journal', 'url_previous_journal' in journal model

- setup.py
- tests/test_issue.py
Realiza um ajuste em um teste errado!
Nos seguintes módulos: 
- setup.py>22
- tests/test_issue.py:50
Executando os testes unitários: `python setup.py test`
Não 
Agora todos os testes estão rodando corretamente: 
Não há tíquetes para esse PR
N/A
> Ajusta teste quebrado e fixa as versões de algumas dependências

- opac_schema/v1/models.py
Cria índices para `scielo_pids`
por commits
n/a
n/a
n/a
https://github.com/scieloorg/opac/issues/1977
- https://docs.mongodb.com/manual/tutorial/analyze-query-plan/
- https://docs.mongodb.com/manual/reference/operator/query/exists/
- https://docs.mongodb.com/manual/core/index-multikey/#std-label-multikey-embedded-documents
- https://docs.mongodb.com/manual/tutorial/sort-results-with-indexes/
- https://mongoengine.readthedocs.io/en/latest/guide/defining-documents.html#compound-indexes-and-indexing-sub-documents
- https://mongoengine.readthedocs.io/en/latest/guide/querying.html
- https://docs.mongodb.com/manual/core/index-compound/#create-a-compound-index
- https://docs.mongodb.com/manual/tutorial/query-arrays/
> Cria índices para `scielo_pids`

- opac_schema/v1/models.py
- setup.py
Atualiza versão para v2.57 no setup.py
> Atualiza versão para v2.57 no setup.py

- opac_schema/v2/models.py
> Corrige o atributo `save`

- opac_schema/v1/models.py
- tests/test_article.py
Adiciona uma entidade para ser responsável por relações entre documentos.
Por commit.
Executando os testes.
N/A 
N/A
https://github.com/scieloorg/opac/issues/2052
N/A
> Adiciona a entidade related_articles

- opac_schema/v1/models.py
- setup.py
Adiciona o campo is_draft no modelo de Pages.
> Adiciona o campo is_draft no modelo de pages. 

- opac_schema/v1/models.py
- tests/test_article.py
Adicionar DOI em multi-idioma.
Por commit 
Sugiro rodar os teste automáticos.
```
python setup.py test
```
N/A.
N/A.
#98 
N/A.
> Adicionar DOI em multi-idioma.

- opac_schema/v1/models.py
- setup.py
- tests/test_article.py
Adiciona um novo modelo para acomodar material suplementar
Pelo módulo **models.py** 
Sugiro rodar os testes automáticos.
N/A
N/A
N/A
N/A
> Adiciona um novo modelo para acomodar material suplementar

- opac_schema/v1/models.py
Adiciona campo old_information_page em Journal
pelos commits
n/a
n/a
n/a
n/a
n/a
> Adiciona campo old_information_page em Journal

- opac_schema/v1/models.py
Adiciona o campo href em RelatedArticle
pelos commits
N/A
N/A
N/A
#111 
N/A
> Adiciona o campo href em RelatedArticle

- opac_schema/v1/models.py
Adiciona o modelo Collab e o campo Article.collabs
pelos commits
N/A
N/A
#112 
N/A
> Adiciona o modelo Collab e o campo Article.collabs
